import random
a = random.randint(0, 9)
b = random.randint(0, 9)
c = random.randint(0, 9)
code_3 = str(a) + str(b) + str(c)
x = random.randint(1, 6)
y = random.randint(1, 6)
z = random.randint(1, 6)
t = random.randint(1, 6)
code_4 = str(x) + str(y) + str(z) + str(t)
print("3-digit code:", code_3)
print("4-digit code:", code_4)