num1 = int(input("enter the first number: "))
num2 = int(input("enter the second number: "))
num3 = int(input("enter the third number: "))
print ("The sum of three numbers is ", num1 + num2 + num3)
print ("the product of three numbers is ", num1 * num2 * num3)
print ("the average of three numbers is ", (num1 + num2 + num3) / 3)